blank_issues_enabled: false
contact_links:
  - name: Sherlock Discord Support Server
    url: https://discord.gg/aneMGtE
    about: Need help? Please reach out to us via our Discord Support Server and we will assist you the best way we can